version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Warsaw
  open-pull-requests-limit: 2
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Warsaw
  open-pull-requests-limit: 2
