FROM golang:1.17rc2-alpine

ENV CGO_ENABLED=0
ENV GO111MODULE=on

WORKDIR /go/src/github.com/AirHelp/filler
RUN apk add --no-cache git

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
CMD ["go", "test", "-cover", "-v", "./..."]
