apiVersion: v1
kind: Pod
metadata:
  labels:
    app: golang
spec:
  containers:
  - name: golang
    image: golang:1.11.2-alpine
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
