version: 3

includes:
  tests: 
    taskfile: tests/Taskfile.yaml
    dir: tests

vars:
  VERSION: 0.2.1

tasks:
  build: go build 

  build:image:
    cmds:
    - finch build --platform linux/arm64,linux/amd64 -t filler:{{ .VERSION }} . 

  push:image:
    cmds:
    - finch push --all-platforms filler:{{ .VERSION }}

  build-and-test:
  - task: build
  - task: tests:run
