name: tests
permissions:
  contents: read

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: "go.mod"

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test -v -cover -race ./...

      - name: Run Go Vet
        run: go vet ./...
