name: tests
permissions:
  contents: read

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
        with:
          go-version-file: "go.mod"

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test -v -cover -race ./...

      - name: Run Go Vet
        run: go vet ./...
